# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jogo_forca.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Forca(object):
    def setupUi(self, Forca):
        Forca.setObjectName("Forca")
        Forca.resize(500, 500)
        Forca.setMinimumSize(QtCore.QSize(500, 500))
        Forca.setMaximumSize(QtCore.QSize(500, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../img/forca.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Forca.setWindowIcon(icon)
        Forca.setStyleSheet("background: black;")
        self.titulo_forca1 = QtWidgets.QLabel(Forca)
        self.titulo_forca1.setGeometry(QtCore.QRect(110, 20, 291, 40))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.titulo_forca1.setFont(font)
        self.titulo_forca1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.titulo_forca1.setStyleSheet("color:rgb(0, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.titulo_forca1.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_forca1.setObjectName("titulo_forca1")
        self.titulo_forca = QtWidgets.QLabel(Forca)
        self.titulo_forca.setGeometry(QtCore.QRect(109, 27, 291, 30))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.titulo_forca.setFont(font)
        self.titulo_forca.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.titulo_forca.setStyleSheet("background-color: rgba(255, 85, 127, 0);\n"
"color: rgb(255, 85, 127);")
        self.titulo_forca.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_forca.setObjectName("titulo_forca")
        self.dica = QtWidgets.QLabel(Forca)
        self.dica.setGeometry(QtCore.QRect(150, 101, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setBold(True)
        font.setWeight(75)
        self.dica.setFont(font)
        self.dica.setStyleSheet("background: black;\n"
"color: white;\n"
"border: 1px solid rgb(255, 85, 127);\n"
"padding: 5px;\n"
"")
        self.dica.setText("")
        self.dica.setAlignment(QtCore.Qt.AlignCenter)
        self.dica.setObjectName("dica")
        self.input_inserir = QtWidgets.QLineEdit(Forca)
        self.input_inserir.setGeometry(QtCore.QRect(150, 420, 113, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(-1)
        self.input_inserir.setFont(font)
        self.input_inserir.setStyleSheet("border: 1px solid rgb(255, 85, 127);\n"
"color: white;\n"
"background-color: black;\n"
"font-size:10px;")
        self.input_inserir.setText("")
        self.input_inserir.setMaxLength(1)
        self.input_inserir.setAlignment(QtCore.Qt.AlignCenter)
        self.input_inserir.setObjectName("input_inserir")
        self.botao_inserir = QtWidgets.QPushButton(Forca)
        self.botao_inserir.setGeometry(QtCore.QRect(271, 420, 90, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.botao_inserir.setFont(font)
        self.botao_inserir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_inserir.setStyleSheet("background: black;\n"
"color: white;\n"
"border: 1px solid rgb(0, 255, 255);\n"
"font-size: 10px;")
        self.botao_inserir.setObjectName("botao_inserir")
        self.palavraOculta = QtWidgets.QLabel(Forca)
        self.palavraOculta.setGeometry(QtCore.QRect(150, 340, 211, 31))
        self.palavraOculta.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(0, 255, 255);\n"
"color: white;")
        self.palavraOculta.setText("")
        self.palavraOculta.setAlignment(QtCore.Qt.AlignCenter)
        self.palavraOculta.setObjectName("palavraOculta")
        self.txt_dica = QtWidgets.QLabel(Forca)
        self.txt_dica.setGeometry(QtCore.QRect(234, 80, 47, 16))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txt_dica.setFont(font)
        self.txt_dica.setStyleSheet("color: rgb(255, 85, 127);")
        self.txt_dica.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_dica.setObjectName("txt_dica")
        self.forcaDesenho = QtWidgets.QLabel(Forca)
        self.forcaDesenho.setGeometry(QtCore.QRect(170, 150, 141, 171))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.forcaDesenho.setFont(font)
        self.forcaDesenho.setStyleSheet("color: white;")
        self.forcaDesenho.setText("")
        self.forcaDesenho.setAlignment(QtCore.Qt.AlignCenter)
        self.forcaDesenho.setObjectName("forcaDesenho")
        self.titulo_forca.raise_()
        self.titulo_forca1.raise_()
        self.dica.raise_()
        self.input_inserir.raise_()
        self.botao_inserir.raise_()
        self.palavraOculta.raise_()
        self.txt_dica.raise_()
        self.forcaDesenho.raise_()

        self.retranslateUi(Forca)
        QtCore.QMetaObject.connectSlotsByName(Forca)

    def retranslateUi(self, Forca):
        _translate = QtCore.QCoreApplication.translate
        Forca.setWindowTitle(_translate("Forca", "Jogo da Forca"))
        self.titulo_forca1.setText(_translate("Forca", "JOGO DA FORCA"))
        self.titulo_forca.setText(_translate("Forca", "JOGO DA FORCA"))
        self.botao_inserir.setText(_translate("Forca", "INSERIR"))
        self.txt_dica.setText(_translate("Forca", "DICA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Forca = QtWidgets.QDialog()
    ui = Ui_Forca()
    ui.setupUi(Forca)
    Forca.show()
    sys.exit(app.exec_())
